FROM python:3.11-slim

WORKDIR /app
# Install all dependencies (including dev)
RUN pip install --no-cache-dir poetry
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false \
    && poetry install --no-root --no-interaction --no-ansi

ENV PYTHONPATH="${PYTHONPATH}:/app"

CMD ["python"]