FROM python:3.14-slim

WORKDIR /app
# Install all dependencies (including dev)
RUN pip install --no-cache-dir poetry
COPY . ./
RUN poetry config virtualenvs.create false \
    && poetry lock && poetry install --no-root --no-interaction --no-ansi

ENV PYTHONPATH="${PYTHONPATH}:/app"

CMD ["python"]
